@startuml system
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!define DEVICONS https://raw.githubusercontent.com/tupadr3/plantuml-icon-font-sprites/master/devicons
!include DEVICONS/clojure.puml

Person(customer, "Clientes", "Detentor da conta de pagamento para vendas")
System(spe, "Sistema de Pagamentos Externo", "Estabelecimento comercial que realizou a venda")


System(processor, "Processador de Pagamentos","Aplicação responsável por processar pagamentos e aplicar taxas e disponibilizar informações", $sprite=clojure)

Rel_R(spe, processor, "Envia transação para processamento em", "HTTP")

Rel_L(customer, processor, "Consulta saldo e transações em", "HTTP")

@enduml
